environment:
  major: 0
  minor: 2
  patch: 0

version: $(major).$(minor).$(patch)+{branch}-{build}

image: Visual Studio 2019 Preview
configuration: Release

dotnet_csproj:
  patch: true
  version: $(major).$(minor).$(patch)
  file: XMindAPI\XMindAPI.csproj

before_build:
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  - provider: NuGet
    api_key:
      secure: Q8wPLGWf+Cl+0mQWUi6Ov+SkthWfB2P2QElWCSoAnIUTfCkjs/9php/qrAori1xl
    skip_symbols: false
    on:
      branch: master
